name: Build App1 (Nest Container App)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/app1/**"

env:
  PLATFORM_RESOURCE_GROUP: rg-bicep-examples-plat
  DOMAIN_RESOURCE_GROUP: rg-bicep-examples-dmn
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  AZ_CREDS: ${{ secrets.AZ_CREDS }}
  AZ_LOCATION: australiaeast
  KEY_VAULT: kv-bicep-examples-plat
  ACR_HOST: acrbicepexamples.azurecr.io
  DOCKER_IMAGE: app1
  BICEP_TEMPLATE: .bicep/app1-infra.bicep
  DEPLOYMENT_NAME: dp-app1-au

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: ${{ env.AZ_CREDS }}

      - name: Retrieve KV secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ env.KEY_VAULT }}
          secrets: "acr-password, acr-username"
        id: keyvault

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ACR_HOST }}
          username: ${{ steps.keyvault.outputs.acr-username }}
          password: ${{ steps.keyvault.outputs.acr-password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.ACR_HOST }}/${{ env.DOCKER_IMAGE }}
          tags: |
            ${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: apps/app1/.
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy Container App
        uses: azure/arm-deploy@v1
        id: provision
        with:
          deploymentName: ${{ env.DEPLOYMENT_NAME }}
          scope: subscription
          region: ${{ env.AZ_LOCATION }}
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          template: ${{ env.BICEP_TEMPLATE }}
          parameters: >
            platformResourceGroup=${{ env.PLATFORM_RESOURCE_GROUP }}
            domainResourceGroup=${{ env.DOMAIN_RESOURCE_GROUP }}
            dockerImage=${{ env.ACR_HOST }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}
